name: apktool
title: Apktool
adopt-info: apktool
summary: A tool for reverse engineering Android apk files.
description: |
  Apktool is a tool for reverse engineering third-party, closed, binary, Android apps. It can decode resources to nearly original form and rebuild them after making some modifications; it makes it possible to debug smali code step-by-step. It also makes working with apps easier thanks to project-like file structure and automation of some repetitive tasks such as building apk, etc.

  Apktool is NOT intended for piracy and other non-legal uses. It could be used for localizing and adding features, adding support for custom platforms, and other GOOD purposes. Just try to be fair with the authors of an app, that you use and probably like.

confinement: strict
base: core24
grade: stable
compression: lzo
contact: https://github.com/khiemdoan/apktool-snap/issues
issues:
  - https://github.com/khiemdoan/apktool-snap/issues
  - https://github.com/iBotPeaches/Apktool/issues
source-code: https://github.com/iBotPeaches/Apktool
website: https://apktool.org/
license: Apache-2.0

apps:
  apktool:
    command: apktool
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-$SNAP_ARCH
      PATH: $JAVA_HOME/bin:$PATH
    plugs:
      - home
      - removable-media

parts:
  apktool:
    plugin: nil
    build-packages:
      - curl
      - jq
    stage-packages:
      - openjdk-21-jre-headless
    override-build: |
      snapcraftctl build

      # Download
      curl -o $SNAPCRAFT_PART_INSTALL/apktool -L https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool
      url=$(curl -s https://api.github.com/repos/iBotPeaches/Apktool/releases/latest | jq -r ".assets[0].browser_download_url")
      curl -o $SNAPCRAFT_PART_INSTALL/apktool.jar -L $url
      chmod +x $SNAPCRAFT_PART_INSTALL/apktool

      # Set version
      version=$(curl -s https://api.github.com/repos/iBotPeaches/Apktool/releases/latest | jq -r ".name" | sed 's/^v//')
      snapcraftctl set-version $version
